config/routes.rb
# frozen_string_literal: true
require 'split/landing_page'

Stoffi::Application.routes.draw do
  # concerns
  concern :followable do
    put :follow, on: :member
  end

  concern :sortable do
    patch :sort, on: :member
  end

  concern :sourceable do
    resources :sources
  end

  concern :imageable do
    resources :images
  end

  # static pages
  %w(contact about legal old barebone music donate youtube).each do |page|
    get "/#{page}", to: "static##{page}", as: page.to_sym
  end

  # send message
  post '/contact', to: 'static#mail'

  # A/B testing dashboard
  mount Split::Dashboard, at: 'admin/split'

  # search
  get '/search', to: 'search#index'
  get '/search/suggestions'

  # # error pages
  %w( 400 403 404 422 500 502 503 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  # account management
  scope module: :accounts do
    # set up devise
    devise_for :user, path: '', skip: [:registration, :passwords, :unlocks],
                      sign_out_via: [:get, :delete],
                      path_names:
    {
      sign_in: :login,
      sign_out: :logout
    }

    # oauth
    match 'oauth/:action', controller: 'oauth', via: [:get, :post], as: :authorize

    # omniauth
    get 'auth/:provider/callback', to: 'links#create'
    get 'auth/failure', to: 'sessions#new'

    # links to other accounts
    resources :links, except: [:edit, :new]

    # custom devise routes
    as :user do
      # password management
      post   'forgot',           to: 'passwords#create',   as: :user_password
      get    'forgot',           to: 'passwords#new',      as: :new_user_password
      get    'reset',            to: 'passwords#edit',     as: :edit_user_password
      patch  'reset',            to: 'passwords#update'
      put    'reset',            to: 'passwords#update'

      # account management
      get    'cancel',           to: 'accounts#cancel',    as: :cancel_user_registration
      post   'join',             to: 'accounts#create',    as: :user_registration
      get    'join',             to: 'accounts#new',       as: :new_user_registration
      get    'settings(/:tab)',  to: 'accounts#edit',      as: :edit_user_registration
      patch  'settings(/:id)',   to: 'accounts#update',    as: :update_user_registration
      put    'settings(/:id)',   to: 'accounts#update'
      delete 'leave',            to: 'accounts#destroy', as: :leave

      # lock management
      post   'unlock',           to: 'unlocks#create'
      get    'unlock',           to: 'unlocks#new',        as: :new_user_unlock
      get    'unlock(/:id)',     to: 'unlocks#show',       as: :user_unlock

      # custom paths
      get    'dashboard(/:tab)', to: 'accounts#dashboard', as: :dashboard
      get    'me',               to: 'accounts#show',      as: :me
    end
  end

  # media resources
  scope module: :media do
    resources :events, :genres, :songs, :artists, concerns: [:sourceable, :imageable]
    resources :albums, concerns: [:sortable, :sourceable, :imageable]
  end

  # apps
  resources :apps do
    member do
      delete 'revoke'
    end
  end

  # shares
  resources :shares, except: [:new, :edit]

  # charts
  namespace :charts do
    get 'listens_for_user'
    get 'songs_for_user'
    get 'artists_for_user'
    get 'albums_for_user'
    get 'playlists_for_user'
    get 'genres_for_user'
    get 'top_listeners'
    get 'active_users'
  end

  get 'playlists', to: 'static#music'
  post 'playlists', to: 'media/playlists#create'

  # user pages
  scope ':user_slug' do
    as :user do
      scope module: :accounts do
        get '(:tab)', to: 'accounts#show', as: :user, constraints:
          { tab: /listens|activity|toplists/ }
        get 'devices', to: 'accounts#dashboard', as: :devices, tab: :devices
        resources :devices, except: :index
      end
    end

    scope module: :media do
      resources :playlists, only: [:new, :create]
      get    ':playlist_slug',        to: 'playlists#show',   as: :playlist
      put    ':playlist_slug/follow', to: 'playlists#follow', as: :follow_playlist
      patch  ':playlist_slug/sort',   to: 'playlists#sort',   as: :sort_playlist
      get    ':playlist_slug/edit',   to: 'playlists#edit',   as: :edit_playlist
      post   ':playlist_slug',        to: 'playlists#update'
      put    ':playlist_slug',        to: 'playlists#update'
      patch  ':playlist_slug',        to: 'playlists#update'
      delete ':playlist_slug',        to: 'playlists#destroy'
      resources :listens do
        post :end, on: :member
      end
    end
  end

  # root path
  #
  # splitted for A/B testing
  constraints(RootConstraintAbout.new) do
    get '/', to: 'static#about'
  end
  constraints(RootConstraintMusic.new) do
    get '/', to: 'static#music'
  end
  constraints(RootConstraintSearch.new) do
    get '/', to: 'search#index'
  end
  constraints(RootConstraintDashboard.new) do
    devise_scope :user do
      get '/', to: 'accounts/accounts#dashboard'
    end
  end
end

app/models/media.rb
# frozen_string_literal: true
# Copyright (c) 2015 Simplare

# Models and controllers related to media resources such as songs, playlists,
# and artists.
module Media
  def self.use_relative_model_naming?
    true
  end
end

app/models/media/album.rb
# frozen_string_literal: true
# Copyright (c) 2015 Simplare

module Media
  # Describes an album, created by one or more artists, containing songs.
  # FIXME: rename `#title` to `#name`.
  class Album < ActiveRecord::Base
    # concerns
    include Base
    include Sourceable
    include Imageable
    include Rankable
    include Duplicatable
    include Sortable
    include FriendlyId

    # associations
    has_many :album_tracks
    has_many :songs, through: :album_tracks
    has_many :genres, through: :songs
    has_many :listens
    has_many :artists, -> { uniq }, through: :songs
    has_many :playlists, -> { uniq }, through: :songs

    # validations
    validates :title, presence: true

    # The sum of the normalised popularity of the album itself, and the
    # normalised popularity of all its songs.
    def popularity
      p = super
      if songs.count > 0 && p == 0
        p += songs.inject(p) do |sum, x|
          sum + x.popularity
        end
      end
      p
    end

    # The name of the artists of the songs in the album.
    def artist_names
      artists.collect(&:name).to_sentence
    end

    # Find album with same title and set of artists.
    def self.find_by_hash(hash)
      artist_txt = hash[:artist]
      artist_txt = join_artists(hash[:artists]) if hash.key?(:artists)
      where('lower(title) = ?', hash[:title].downcase).find_each do |album|
        return album if join_artists(album.artists) == artist_txt
      end
      nil
    end

    def self.create_by_hash(hash)
      hash.delete :artists
      super hash
    end

    # Paginates the songs of the album. Should be called before
    # <tt>paginated_songs</tt> is called.
    #
    #   album.paginate_songs(10, 30)
    #   songs = album.paginated_songs # songs will now hold the songs 30-39
    def paginate_songs(limit, offset)
      @paginated_songs = []
      songs.limit(limit).offset(offset).each do |song|
        @paginated_songs << song
      end
    end

    # Returns a slice of the album's songs which was created by
    # <tt>paginated_songs</tt>.
    #
    #   album.paginate_songs(10, 30)
    #   songs = album.paginated_songs # songs will now hold the songs 30-39
    attr_reader :paginated_songs

    private_class_method

    # Create a string with all artists that will uniquely describe the
    # set of artists of the song.
    def self.join_artists(artists)
      artists.collect do |artist|
        name = artist
        name = artist.name if artist.is_a?(Media::Artist)
        name = artist[:name] if artist.is_a?(Hash)
        name.downcase.strip.delete("\t")
      end.sort.join("\t")
    end

    # Configure all concerns and extensions.
    def self.configure_concerns
      # Searchable
      searchable do
        text :title, boost: 5
        text :artists do
          artists.map(&:name)
        end
        string :locations, multiple: true do
          sources.map(&:name)
        end
        integer :archetype_id
      end

      # Sortable
      can_sort :songs

      # Enable URLs like `/albums/:name`.
      friendly_id :title, use: :slugged
    end
    configure_concerns
  end
end

app/models/media/album_track.rb
# frozen_string_literal: true
# Copyright (c) 2015 Simplare

module Media
  # An album track, ie. a song and its position in the album.
  class AlbumTrack < ActiveRecord::Base
    belongs_to :album
    belongs_to :song
    validates :album, :song, presence: true
  end
end

app/controllers/media/albums_controller.rb
# frozen_string_literal: true
# Copyright (c) 2015 Simplare

module Media
  # The business logic for song albums.
  class AlbumsController < MediaController
    include ImageableController
    include SortableController

    can_sort :songs

    oauthenticate interactive: true, except: [:index, :show]
    before_action :ensure_admin, only: [:edit, :update, :destroy]

    # GET /albums/1
    def show
    end

    # GET /albums/1/edit
    def edit
    end

    # PATCH /albums/1
    def update
      ids = begin
              params[:songs].map(&:to_i)
            rescue
              nil
            end if params[:songs].is_a? Array
      associate_resources(:songs)
      @album.sort(:songs, ids) if ids.present?
      @album.update_attributes(album_params) if params[:album].present?

      respond_with @album
    end

    # DELETE /albums/1
    def destroy
      @album.destroy
      respond_with @album
    end

    private

    # Create an instance of the resource given the parameters.
    def set_resource
      @resource = @album = Media::Album.friendly.find params[:id]
    rescue ActiveRecord::RecordNotFound
      not_found :album
    end

    # Never trust parameters from the scary internet, only allow the white list
    # through.
    def album_params
      params.require(:album).permit(:title)
    end
  end
end

app/controllers/media/artists_controller.rb
# frozen_string_literal: true
# Copyright (c) 2015 Simplare

module Media
  # The business logic for artists.
  class ArtistsController < MediaController
    include ImageableController

    oauthenticate interactive: true, except: [:index, :show]
    before_action :ensure_admin, except: [:index, :show]

    def show
      l, o = pagination_params
      @artist.paginate_songs(l, o)
      respond_with(@artist, methods: [:paginated_songs])
    end

    def update
      @artist.update(artist_params)
      respond_with(@artist)
    end

    def destroy
      @artist.destroy
      respond_with(@artist)
    end

    private

    # Create an instance of the resource given the parameters.
    def set_resource
      @resource = @artist = Media::Artist.friendly.find params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list
    # through.
    def artist_params
      params.require(:artist).permit(:name)
    end
  end
end

app/controllers/media/events_controller.rb
# frozen_string_literal: true
# Copyright (c) 2015 Simplare

module Media
  # The business logic for events.
  class EventsController < MediaController
    include ImageableController

    before_action :ensure_admin, except: [:index, :show, :create]
    oauthenticate interactive: true, except: [:index, :show]

    # GET /events/1
    def show
    end

    # POST /events
    def create
      @event = Event.new(event_params)

      respond_to do |format|
        if @event.save
          format.html { redirect_to @event }
          format.json { render :show, status: :created, location: @event }
        else
          format.html { render :new }
          format.json do
            render json: @event.errors,
                   status: :unprocessable_entity
          end
        end
      end
    end

    # PATCH /events/1
    def update
      respond_to do |format|
        if @event.update(event_params)
          format.html { redirect_to @event }
          format.json { render :show, status: :ok, location: @event }
        else
          format.html { render :edit }
          format.json do
            render json: @event.errors,
                   status: :unprocessable_entity
          end
        end
      end
    end

    # DELETE /events/1
    def destroy
      @event.destroy
      respond_to do |format|
        format.html { redirect_to events_url }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = @event = Media::Event.friendly.find params[:id]
    rescue ActiveRecord::RecordNotFound
      not_found :event
    end

    # Never trust parameters from the scary internet, only allow the white list
    # through.
    def event_params
      params.require(:event).permit(:name, :venue, :latitude, :longitude,
                                    :start, :stop, :content, :category)
    end
  end
end

app/controllers/media/genres_controller.rb
# frozen_string_literal: true
# Copyright (c) 2015 Simplare

module Media
  # The business logic for genres.
  class GenresController < MediaController
    include ImageableController

    before_action :ensure_admin, except: [:index, :show, :create]
    oauthenticate interactive: true, except: [:index, :show]

    # GET /genres/1
    def show
    end

    # POST /genres
    def create
      @genre = Genre.new(genre_params)

      respond_to do |format|
        if @genre.save
          format.html { redirect_to @genre }
          format.json { render :show, status: :created, location: @genre }
        else
          format.html { render :new }
          format.json do
            render json: @genre.errors, status: :unprocessable_entity
          end
        end
      end
    end

    # PATCH/PUT /genres/1
    def update
      respond_to do |format|
        if @genre.update(genre_params)
          format.html { redirect_to @genre }
          format.json { render :show, status: :ok, location: @genre }
        else
          format.html { render :edit }
          format.json do
            render json: @genre.errors, status: :unprocessable_entity
          end
        end
      end
    end

    # DELETE /genres/1
    def destroy
      @genre.destroy
      respond_to do |format|
        format.html { redirect_to genres_url }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = @genre = Media::Genre.friendly.find params[:id]
    rescue ActiveRecord::RecordNotFound
      not_found :genre
    end

    # Never trust parameters from the scary internet, only allow the white list
    # through.
    def genre_params
      params.require(:genre).permit(:name)
    end
  end
end

app/controllers/media/images_controller.rb
# frozen_string_literal: true
# Copyright (c) 2015 Simplare

module Media
  # Logic for managing images.
  class ImagesController < ApplicationController
    before_action :ensure_admin
    before_action :set_resource, only: [:show, :edit, :update, :destroy]

    # GET /:resource/images
    def index
      @resource = imageable_resource
    end

    # GET /:resource/images/:id
    def show
    end

    # GET /:resource/images/new
    def new
      @image = Image.new
      @image.resource = imageable_resource
    end

    # POST /:resource/images
    def create
      @image = Image.new(image_params)

      respond_to do |format|
        if @image.save
          format.html { redirect_to @image.resource }
          format.json { render :show, status: :created, location: @image }
        else
          format.html { render :new }
          format.json do
            render json: @image.errors, status: :unprocessable_entity
          end
        end
      end
    end

    # GET /:resource/images/:id/edit
    def edit
    end

    # PATCH /:resource/images/:id
    def update
      respond_to do |format|
        if @image.update(image_params)
          format.html do
            redirect_to @image.resource, flash:
              { success: t('media.images.update.success') }
          end
          format.json { render :show, status: :ok, location: @image }
        else
          format.html { render 'edit' }
          format.json do
            render json: @image.errors, status: :unprocessable_entity
          end
        end
      end
    end

    # DELETE /:resource/images/:id
    def destroy
      resource = @image.resource
      @image.destroy
      respond_to do |format|
        format.html do
          redirect_to resource, flash:
            { success: t('media.images.delete.success') }
        end
        format.json { head :no_content }
      end
    end

    private

    def imageable_resource
      klass = 'image'
      id_key = params.keys.find { |x| x.downcase.match('[a-z]+_id') }
      id = params[id_key]
      klass = id_key.downcase.match('([a-z]+)_id')[1]
      "Media::#{klass.classify}".constantize.find(id)
    rescue
      not_found(klass) && (return)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      not_found('image') && return unless Image.exists? params[:id]
      @image = Image.find(params[:id])
    end

    # Access the resource for this controller.
    def resource
      @image
    end

    # Never trust parameters from the scary internet, only allow the white list
    # through.
    def image_params
      params.require(:image).permit(:url, :resource_id, :resource_type)
    end

    def image_url(image, options = {})
      klass = image.resource.class.name.demodulize.parameterize
      send("#{klass}_image_url", image.resource, image, options)
    end
  end
end

app/views/media/songs/_song.html.haml
- link_options = {}
- link_options[:dedup] = true if local_assigns[:archetype].present?
- link_path = song_path song, link_options
- options = { data: { 'resource-id' => song.id }, url: link_path }
    
= media_list_item song, options do |m|

  - m.title song, badge: local_assigns[:badge].present?, url: link_path
  
  - m.buttons do
  
    - if local_assigns[:archetype].present? and current_user.admin?
      - arch = local_assigns[:archetype]
      %a.btn.btn-xs.btn-link{ data: { 'ng-click' => "toggleDup(#{song.id})" } }
        %span.fa.fa-minus{ data: { 'ng-show' => "isDup(#{song.id})" } }
        %span.fa.fa-plus{ data: { 'ng-hide' => "isDup(#{song.id})" } }
        = t 'media.songs.toggle_duplicate'
          
    = render partial: 'media/playlists/menu', locals: { songs: [song.id] }
      
    = link_to '#', class: 'btn btn-xs btn-link' do
      %span.fa.fa-fw.fa-play
      = t 'media.songs.play'
  
  / content
  %span.fa.fa-fw.fa-user
  = link_to_association song.artists

app/views/media/songs/edit.html.haml
- content_for :title do
  = t 'media.songs.edit.title', song: @song
  
- heading = t 'media.songs.edit.heading', song: @song
- form_url = song_path(@song)
- back_url = form_url
- method = :patch
- init = "fetch('#{song_url(@song, format: :json, dedup: true)}')"
- form_data = { 'ng-controller' => 'SongController', 'ng-init' => init }
- base_url = "#{request.protocol}#{request.host_with_port}"

- content_for :toolbar do

  .navbar-left
    = simple_format heading, wrapper_tag: :h3, class: 'toolbar-title'
  
  .navbar-right
    %button.btn.btn-primary{ data: { 'toolbar-submit' => '' }}
      %span.fa.fa-check
      = t 'save'
    = link_to back_url, target: '_self', class: 'btn btn-secondary' do
      %span.fa.fa-remove
      = t 'cancel'

= form_for @song, url: form_url, method: method, data: form_data do |f|

  = render partial: 'shared/messages', locals: { resource: @song }

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :slug
    .input-group
      %span.input-group-addon
        = "#{base_url}/songs/"
      = f.text_field :slug, class: 'form-control'
  
  = hidden_field_tag "artists[][name]", "{{artist}}", mutiple: true,
      data: { 'ng-repeat' => "artist in artists" }
      
  = hidden_field_tag 'song[genre]', "{{genreParam()}}"
    
  .form-group.fuelux
    = f.label :artists
    .pillbox#myPillbox{ data: { 'stf-pillbox' => '',
          'stf-pillbox-add' => "addArtist",
          'stf-pillbox-remove' => "removeArtist" } }
      %ul.clearfix.pill-group
        %li.btn.btn-default.pill{ data: { 'ng-repeat' => 'artist in artists',
            value: '{{artist}}' } }
          %span {{artist}}
          %span.glyphicon.glyphicon-close
            %span.sr-only Remove
        
        %li.pillbox-input-wrap.btn-group
          %input.form-control.dropdown-toggle.pillbox-add-item{ type: :text,
            placeholder: 'Add artist',
            data: { 'stf-autocomplete' => '/search/suggestions.json?c=artists' } }
          %ul.suggest.dropdown-menu{ role: :menu,
            data: { toggle: :dropdown, flip: :auto }}
    
  .form-group.fuelux
    = f.label :genres
    .pillbox#myPillbox{ data: { 'stf-pillbox' => '',
          'stf-pillbox-add' => "addGenre",
          'stf-pillbox-remove' => "removeGenre" } }
      %ul.clearfix.pill-group
        %li.btn.btn-default.pill{ data: { 'ng-repeat' => 'genre in genres',
            value: '{{genre}}' } }
          %span {{genre}}
          %span.glyphicon.glyphicon-close
            %span.sr-only Remove
        
        %li.pillbox-input-wrap.btn-group
          %input.form-control.dropdown-toggle.pillbox-add-item{ type: :text,
            placeholder: 'Add genre',
            data: { 'stf-autocomplete' => '/search/suggestions.json?c=genres' } }
          %ul.suggest.dropdown-menu{ role: :menu,
            data: { toggle: :dropdown, flip: :auto }}

app/views/media/songs/index.js.erb
<%= @songs.map do |song|
  render partial: song, layout: 'shared/media_list_item.html'
end.to_s.html_safe
%>

app/views/media/songs/show.html.haml
- content_for :title do
  = @song.title

- content_for :header do
  %meta{ property: 'og:title', content: @song.title }
  %meta{ property: 'og:type', content: 'music.song' }
  %meta{ property: 'og:image', content: image_for(@song) }
  %meta{ property: 'og:url', content: song_url(@song) }
  - @song.artists.each do |artist|
    %meta{ property: 'music:musician', content: artist_url(artist) }
  - @song.albums.each do |album|
    %meta{ property: 'music:album', content: album_url(album) }

%div{ data: { 'ng-controller' => 'SongController',
  'ng-init' => "fetch('#{song_url(@song, format: :json)}')" }}
  
  = cover_for @song do |m|
  
    - m.buttons do
      = render partial: '/media/playlists/menu',
          locals: { size: :md, songs: [@song.id] }
      %a.btn.btn-primary
        %span.fa.fa-fw.fa-play
    
    - m.subheading = link_to_association @song.artists
        
    .cover-meta
      %span.fa.fa-fw.fa-tags
      = link_to_association @song.genres.limit(3)

  .row
    .col-md-8
      = render @song.sources
      = media_list @song.albums, t('media.songs.albums')
      = media_list @song.similar, t('media.songs.similar'), show_empty: false,
          archetype: @song
      - if current_user.admin?
        = media_list @song.duplicates, t('media.songs.duplicates'),
            show_empty: false, archetype: @song
        = media_list @song.duplicate_candidates,
            t('media.songs.duplicate_candidates'),
            show_empty: false, archetype: @song
    
    .col-md-4
      - if current_user.admin? or @song.sources.any?
        = render partial: '/media/sources/index', locals: { resource: @song }
      - %w(stats artists manage).each do |panel|
        = render "/media/songs/show/#{panel}"