config/routes.rb
# frozen_string_literal: true
require 'split/landing_page'

Stoffi::Application.routes.draw do
  # concerns
  concern :followable do
    put :follow, on: :member
  end

  concern :sortable do
    patch :sort, on: :member
  end

  concern :sourceable do
    resources :sources
  end

  concern :imageable do
    resources :images
  end

  # static pages
  %w(contact about legal old barebone music donate youtube).each do |page|
    get "/#{page}", to: "static##{page}", as: page.to_sym
  end

  # send message
  post '/contact', to: 'static#mail'

  # A/B testing dashboard
  mount Split::Dashboard, at: 'admin/split'

  # search
  get '/search', to: 'search#index'
  get '/search/suggestions'

  # # error pages
  %w( 400 403 404 422 500 502 503 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  # account management
  scope module: :accounts do
    # set up devise
    devise_for :user, path: '', skip: [:registration, :passwords, :unlocks],
                      sign_out_via: [:get, :delete],
                      path_names:
    {
      sign_in: :login,
      sign_out: :logout
    }

    # oauth
    match 'oauth/:action', controller: 'oauth', via: [:get, :post], as: :authorize

    # omniauth
    get 'auth/:provider/callback', to: 'links#create'
    get 'auth/failure', to: 'sessions#new'

    # links to other accounts
    resources :links, except: [:edit, :new]

    # custom devise routes
    as :user do
      # password management
      post   'forgot',           to: 'passwords#create',   as: :user_password
      get    'forgot',           to: 'passwords#new',      as: :new_user_password
      get    'reset',            to: 'passwords#edit',     as: :edit_user_password
      patch  'reset',            to: 'passwords#update'
      put    'reset',            to: 'passwords#update'

      # account management
      get    'cancel',           to: 'accounts#cancel',    as: :cancel_user_registration
      post   'join',             to: 'accounts#create',    as: :user_registration
      get    'join',             to: 'accounts#new',       as: :new_user_registration
      get    'settings(/:tab)',  to: 'accounts#edit',      as: :edit_user_registration
      patch  'settings(/:id)',   to: 'accounts#update',    as: :update_user_registration
      put    'settings(/:id)',   to: 'accounts#update'
      delete 'leave',            to: 'accounts#destroy', as: :leave

      # lock management
      post   'unlock',           to: 'unlocks#create'
      get    'unlock',           to: 'unlocks#new',        as: :new_user_unlock
      get    'unlock(/:id)',     to: 'unlocks#show',       as: :user_unlock

      # custom paths
      get    'dashboard(/:tab)', to: 'accounts#dashboard', as: :dashboard
      get    'me',               to: 'accounts#show',      as: :me
    end
  end

  # media resources
  scope module: :media do
    resources :events, :genres, :songs, :artists, concerns: [:sourceable, :imageable]
    resources :albums, concerns: [:sortable, :sourceable, :imageable]
  end

  # apps
  resources :apps do
    member do
      delete 'revoke'
    end
  end

  # shares
  resources :shares, except: [:new, :edit]

  # charts
  namespace :charts do
    get 'listens_for_user'
    get 'songs_for_user'
    get 'artists_for_user'
    get 'albums_for_user'
    get 'playlists_for_user'
    get 'genres_for_user'
    get 'top_listeners'
    get 'active_users'
  end

  get 'playlists', to: 'static#music'
  post 'playlists', to: 'media/playlists#create'

  # user pages
  scope ':user_slug' do
    as :user do
      scope module: :accounts do
        get '(:tab)', to: 'accounts#show', as: :user, constraints:
          { tab: /listens|activity|toplists/ }
        get 'devices', to: 'accounts#dashboard', as: :devices, tab: :devices
        resources :devices, except: :index
      end
    end

    scope module: :media do
      resources :playlists, only: [:new, :create]
      get    ':playlist_slug',        to: 'playlists#show',   as: :playlist
      put    ':playlist_slug/follow', to: 'playlists#follow', as: :follow_playlist
      patch  ':playlist_slug/sort',   to: 'playlists#sort',   as: :sort_playlist
      get    ':playlist_slug/edit',   to: 'playlists#edit',   as: :edit_playlist
      post   ':playlist_slug',        to: 'playlists#update'
      put    ':playlist_slug',        to: 'playlists#update'
      patch  ':playlist_slug',        to: 'playlists#update'
      delete ':playlist_slug',        to: 'playlists#destroy'
      resources :listens do
        post :end, on: :member
      end
    end
  end

  # root path
  #
  # splitted for A/B testing
  constraints(RootConstraintAbout.new) do
    get '/', to: 'static#about'
  end
  constraints(RootConstraintMusic.new) do
    get '/', to: 'static#music'
  end
  constraints(RootConstraintSearch.new) do
    get '/', to: 'search#index'
  end
  constraints(RootConstraintDashboard.new) do
    devise_scope :user do
      get '/', to: 'accounts/accounts#dashboard'
    end
  end
end

app/views/apps/_app.html.erb
<li class='item' data-href='<%= url_for app %>'
  data-resource-id='<%= app.id %>' data-resource-type='app'
	data-resource-url='<%= url_for app %>'>
	
	<!-- image -->
	<%= image_tag app.image(:huge), data: { field: :picture } %>
	
	<!-- meta data -->
	<div class='overlay'>
		<span class='title' data-field='display'><%= app %></span>
		
		<% if defined? type and type %>
			<span class='type' data-list-mode='grid' data-type='app'>
			  <%= t 'apps.singular' %>
			</span>
		<% end %>
		
		<span class='description'>
			<%= t 'apps.description_html', author: link_to(username(app.user),
			  url_for(app.user)) %>
		</span>
		
	</div>
	
	<!-- controls -->
	<div class='action-bar'>
		
		<% if defined? type and type %>
			<span class='type' data-list-mode='list' data-type='app'>
			  <%= t 'apps.singular' %>
			</span>
		<% end %>
		
		<% if current_user.owns?(app) or current_user.admin? %>
			<span class='edit action'>
				<%= link_to t('pages.apps.edit.link'), edit_app_path(app) %>
			</span>
		<% end %>
		
		<% if user_signed_in? %>
			<% if current_user.owns?(app) or current_user.admin? %>
				<span class='remove action'>
					<%= link_to '', title: t('pages.apps.destroy.description'),
					  data: {
						  ajax_call: :delete,
  						ajax_url: app_path(app, format: :json),
  						ajax_method: :delete,
  						confirm: t('pages.apps.destroy.confirm', app: app)
  					} do %>
						<span data-list-mode='list'>
						  <%= t 'pages.apps.destroy.link' %>
						</span>
						<span data-list-mode='grid'>x</span>
					<% end %>
				</span>
			<% end %>
			
			<span class='action'>
				<% if app.installed_by? current_user %>
					<%= link_to revoke_app_path(app, return_uri: request.url), method:
					  :delete do %>
						<span data-list-mode='list'>
						  <%= t 'pages.apps.revoke.link' %>
						</span>
						<span data-list-mode='grid'>-</span>
					<% end %>
				<% else %>
					<%= link_to authorize_path(client_id: app.key, redirect_uri:
					  request.url, response_type: :token) do %>
						<span data-list-mode='list'>
						  <%= t 'pages.apps.authorize.link' %>
						</span>
						<span data-list-mode='grid'>+</span>
					<% end %>
				<% end %>
			</span>
				
		<% end %>
		
	</div>
</li>

app/views/apps/_form.html.erb
<%= render partial: 'shared/messages', locals: { resource: @app } %>

<%= form_for @app do |f| %>
	<div class='field'>
		<%= f.label :name, t("apps.meta.name") %>
		<%= f.text_field :name, autofocus: true %>
	</div>
	<div class='field'>
		<%= f.label :name, t("apps.meta.description") %>
		<%= f.text_area :description %>
	</div>
	<div class='field'>
		<%= f.label :name, t("apps.meta.website") %>
		<%= f.url_field :website %>
	</div>
	
	<p>&nbsp;</p>
		
	<div class='field'>
		<%= f.label :icon_16, t("apps.meta.icon_16") %>
		<%= f.url_field :icon_16 %>
		<%= image_tag '', width: 16, height: 16, id: :icon_16 %>
	</div>
	<div class='field'>
		<%= f.label :icon_64, t("apps.meta.icon_64") %>
		<%= f.url_field :icon_64 %>
		<%= image_tag '', width: 64, height: 64, id: :icon_64 %>
	</div>
	<div class='field'>
		<%= f.label :icon_512, t("apps.meta.icon_512") %>
		<%= f.url_field :icon_512 %>
		<%= image_tag '', width: 64, height: 64, id: :icon_512 %>
	</div>
	
	<p>&nbsp;</p>
	
	<div class='field'>
		<%= f.label :name, t("apps.meta.author") %>
		<%= f.text_field :author %>
	</div>
	<div class='field'>
		<%= f.label :name, t("apps.meta.author_url") %>
		<%= f.url_field :author_url %>
	</div>
	
	<p>&nbsp;</p>
	
	<div class='field'>
		<%= f.label :name, t("apps.meta.callback") %>
		<%= f.url_field :callback_url %>
	</div>
	<div class='field'>
		<%= f.label :name, t("apps.meta.support_url") %>
		<%= f.url_field :support_url %>
	</div>
	
	<%= link_to '#', class: 'button', data: { button: :submit } do %>
		<%= image_tag 'gfx/buttons/save.png' %>
		<span><%=t 'save' %></span>
	<% end %>
	
	
<% end %>

app/views/apps/_form.html.haml
- if @app.new_record?
  - heading = t 'apps.new.heading'
  - back_url = apps_path
- else
  - heading = t 'apps.edit.heading', app: @app
  - back_url = app_path(@app)

- content_for :toolbar do

  .navbar-left
    = simple_format heading, wrapper_tag: :h3, class: 'toolbar-title'
  
  .navbar-right
    %button.btn.btn-primary{ data: { 'toolbar-submit' => '' }}
      %span.fa.fa-check
      = t 'save'
    = link_to back_url, target: '_self', class: 'btn btn-secondary' do
      %span.fa.fa-remove
      = t 'cancel'

= form_for @app do |f|

  = render partial: 'shared/messages', locals: { resource: @app }

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :description
    = f.text_field :description, class: 'form-control'

  .form-group
    = f.label :website
    = f.text_field :website, class: 'form-control'

  .form-group
    = f.label :author
    = f.text_field :author, class: 'form-control'

  .form-group
    = f.label :author_url
    = f.text_field :author_url, class: 'form-control'

  .form-group
    = f.label :callback_url
    = f.text_field :callback_url, class: 'form-control'

  .form-group
    = f.label :support_url
    = f.text_field :support_url, class: 'form-control'

app/views/apps/_form2.html.erb
<%= render partial: 'shared/messages', locals: { resource: @app } %>

<%= form_for @app do |f| %>
	<div class='field'>
		<%= f.label :name, t("apps.meta.name") %>
		<%= f.text_field :name, autofocus: true %>
	</div>
	<div class='field'>
		<%= f.label :name, t("apps.meta.description") %>
		<%= f.text_area :description %>
	</div>
	<div class='field'>
		<%= f.label :name, t("apps.meta.website") %>
		<%= f.url_field :website %>
	</div>
	
	<p>&nbsp;</p>
		
	<div class='field'>
		<%= f.label :icon_16, t("apps.meta.icon_16") %>
		<%= f.url_field :icon_16 %>
		<%= image_tag '', width: 16, height: 16, id: :icon_16 %>
	</div>
	<div class='field'>
		<%= f.label :icon_64, t("apps.meta.icon_64") %>
		<%= f.url_field :icon_64 %>
		<%= image_tag '', width: 64, height: 64, id: :icon_64 %>
	</div>
	<div class='field'>
		<%= f.label :icon_512, t("apps.meta.icon_512") %>
		<%= f.url_field :icon_512 %>
		<%= image_tag '', width: 64, height: 64, id: :icon_512 %>
	</div>
	
	<p>&nbsp;</p>
	
	<div class='field'>
		<%= f.label :name, t("apps.meta.author") %>
		<%= f.text_field :author %>
	</div>
	<div class='field'>
		<%= f.label :name, t("apps.meta.author_url") %>
		<%= f.url_field :author_url %>
	</div>
	
	<p>&nbsp;</p>
	
	<div class='field'>
		<%= f.label :name, t("apps.meta.callback") %>
		<%= f.url_field :callback_url %>
	</div>
	<div class='field'>
		<%= f.label :name, t("apps.meta.support_url") %>
		<%= f.url_field :support_url %>
	</div>
	
	<%= link_to '#', class: 'button', data: { button: :submit } do %>
		<%= image_tag 'gfx/buttons/save.png' %>
		<span><%=t 'save' %></span>
	<% end %>
	
	
<% end %>

app/views/apps/edit.html.haml
- content_for :title do
  = t 'apps.edit.title', app: @app.name
= render 'form'

app/views/apps/index.html.erb
<%= render partial: 'shared/lists/top', locals: {
	resource: 'apps',
	tabs: ['apps', 'added', 'created'],
	categories: [''],
	locals: {
		created: { show_add_button: { mode: :page } }
	}
} %>

app/views/apps/index.html.haml
.pull-right
  = link_to new_app_path, class: 'btn btn-primary', target: '_self' do
    %span.fa.fa-plus
    Create app
%h2 Apps
= @apps.each_slice(4) do |app_row|
  .row
    - app_row.each do |app|
      .col-sm-3
        .thumbnail
          = image_tag 'http://placehold.it/250x200'
          .caption
            .app-button.pull-right
              = link_to '#', class: 'btn btn-primary btn-xs', target: '_self' do
                %span.fa.fa-plus
                Install
            .app-title
              %strong
                = app.name
            .app-author.clearfix
              = link_to app.author, app.author_url

app/views/apps/index2.html.erb
<%= render partial: 'shared/lists/top', locals: {
	resource: 'apps',
	tabs: ['apps', 'added', 'created'],
	categories: [''],
	locals: {
		created: { show_add_button: { mode: :page } }
	}
} %>

app/views/apps/new.html.haml
- content_for :title do
  = t 'apps.new.title'
= render 'form'

app/views/apps/show.html.haml
- content_for :title do
  = @app.name

- content_for :description do
  =t 'pages.apps.show.description', app: @app

%div
  
  = cover_for @app do |m|
    - m.buttons do
      %a.btn.btn-primary
        %span.fa.fa-fw.fa-add
        = t 'apps.install'
        
    .cover-meta
      %span.fa.fa-fw.fa-user
      = link_to @app.author, @app.author_url

  .row
    .col-md-8
      %p TODO
    
    .col-md-4
      - %w(info manage).each do |panel|
        = render "/apps/show/#{panel}"

app/views/apps/show2.html.erb
<% content_for :title do %>
	<%= @app.name %>
<% end %>

<% content_for :description do %>
	<%=t 'pages.apps.show.description', app: @app %>
<% end %>

<% if false %>
<article class='tabbed' data-resource-type='app'
  data-resource-id='<%= @app.id %>' data-resource-url='<%= url_for @app %>'>
	<section class='head'>
		<div class='left'>
			<div class='top'></div>
			<div class='line'></div>
			<div class='bottom'>
				<span><%=t 'apps.singular' %></span>
			</div>
		</div>
		<div class='right'>
			<div class='top'>
				<h1 data-field='display'><%=d @app.name %></h1>
				<%= render partial: 'shared/social' %>
			</div>
			<div class='line'></div>
			<div class='bottom'>
				<span>
					<%= t 'apps.description_html', author: link_to(@app.user) %>
				</span>
			</div>
		</div>
		<div class='image'>
			<div class='image-border'>
				<%= image_tag @app.image(:huge), data: { field: :picture } %>
			</div>
		</div>
	</section>
	
	<!-- we don't have any tabs, but need this to create the shadow effect -->
	<section class='tabs'></section>
	
	<aside>
		<section data-type='bonus'>
			<%= render 'shared/ads/skyscraper' %>
		</section>
	</aside>
	
	<% if @app.installed_by? current_user %>
		<%= link_to t('pages.apps.revoke.link'), revoke_app_path(@app, return_uri:
		  request.url), method: :delete, class: 'button', id: 'uninstall_button' %>
	<% elsif user_signed_in? %>
		<%= link_to t('pages.apps.authorize.link'), authorize_path(client_id:
		  @app.key, redirect_uri: request.url, response_type: :token),
			class: 'button', id: 'install_button' %>
	<% end %>
	
	<%= render 'apps/sections/info' %>
	<!-- TODO: fix the sunspot search so we get results here -->
	<% #render 'apps/sections/similar' %>
	
	<% if current_user.owns?(@app) or current_user.admin? %>
		<section>
			<%= link_to edit_app_path(@app), class: 'button primary' do %>
				<span><%= t 'pages.apps.edit.link' %></span>
			<% end %>
			<%= link_to t('pages.apps.destroy.link'), app_path(@app), method:
			  :delete, data: {
				confirm: t('pages.apps.destroy.confirm')
			} %>
		</section>
	<% end %>
	
</article>
<% end %>